// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Season, SeasonData, SeasonTableId } from "./tables/Season.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { Ownable, OwnableTableId } from "./tables/Ownable.sol";
import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { Board, BoardData, BoardTableId } from "./tables/Board.sol";
import { MapBoard, MapBoardTableId } from "./tables/MapBoard.sol";
import { RandomList, RandomListData, RandomListTableId } from "./tables/RandomList.sol";
import { BattleList, BattleListData, BattleListTableId } from "./tables/BattleList.sol";
import { PlayerLocationLock, PlayerLocationLockTableId } from "./tables/PlayerLocationLock.sol";
import { BoxList, BoxListData, BoxListTableId } from "./tables/BoxList.sol";
