// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapData, MapDataData, MapDataTableId } from "./tables/MapData.sol";
import { Season, SeasonData, SeasonTableId } from "./tables/Season.sol";
