// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  function initMap(int[] calldata array, uint xLen, uint yLen) external;

  function getPos(uint x, uint y) external view returns (bool);
}
