[profile.default]
solc = "0.8.21"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

[profile.lattice-testnet]
eth_rpc_url = "https://follower.testnet-chain.linfra.xyz"


[profile.arb-testnet]
eth_rpc_url = "https://arbitrum-goerli.infura.io/v3/5ca372516740427e97512d4dfefd9c47"
optimizer = true
optimizer_runs = 3000

[profile.linea-testnet]
eth_rpc_url = "https://linea-goerli.infura.io/v3/5ca372516740427e97512d4dfefd9c47"
optimizer = true
optimizer_runs = 3000

[profile.sepolia-testnet]
eth_rpc_url = "https://sepolia.infura.io/v3/5ca372516740427e97512d4dfefd9c47"
optimizer = true
optimizer_runs = 3000


[profile.Mississippi-testnet]
eth_rpc_url = "http://rpc1.0xMssp.xyz"
optimizer = true
optimizer_runs = 3000


[profile.REDSTONE-HOLESKY]
eth_rpc_url = "https://rpc.holesky.redstone.xyz"
optimizer = true
optimizer_runs = 3000


[profile.scroll-sepolia]
eth_rpc_url = "https://sepolia-rpc.scroll.io"

[profile.optimism-goerli]
eth_rpc_url = "https://goerli.optimism.io"
optimizer = true
optimizer_runs = 3000


[profile.linea-goerli]
eth_rpc_url = "https://linea-goerli.infura.io/v3/8a5edc3264dd435391dad31e754031d6"
optimizer = true
optimizer_runs = 3000
